questions = [
    {
        "question": "I should be able to control my own property.",
        "effect": {
            "econ": -5,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
	    {
        "question": "Private Property should exist.",
        "effect": {
            "econ": -5,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
		    {
        "question": "All Property is Private.",
        "effect": {
            "econ": -10,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
		    {
        "question": "Currency is a baseless idea, that should not exist.",
        "effect": {
            "econ": 10,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
		    {
        "question": "Important things like Education and Healthcare should be public.",
        "effect": {
            "econ": 5,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
		    {
        "question": "The Freer The Market The Freer The People.",
        "effect": {
            "econ": -10,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
		    {
        "question": "From each according to his ability, to each according to his needs.",
        "effect": {
            "econ": 5,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
			    {
        "question": "From each according to his ability, to each according to his needs.",
        "effect": {
            "econ": 5,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
			    {
        "question": "I don't see anything wrong with theft/stealing.",
        "effect": {
            "econ": 10,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
			    {
        "question": "From each according to his ability, to each according to his needs.",
        "effect": {
            "econ": 5,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
				    {
        "question": "An Individual by himself is useless.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": -5,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
				    {
        "question": "An Individual can do much more by himself, than being restricted in a group.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 5,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
					    {
        "question": "A Government/State is harmful for Individual Freedom.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 5,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
					    {
        "question": "The very existance of the state is a spook.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 10,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
					    {
        "question": "We should all think alike.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": -5,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
					    {
        "question": "Egoism is not necessarily bad.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 10,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
					    {
        "question": "I'd rather work in a group than by myself.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": -5,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
					    {
        "question": "Humans are united by nature, and should not act alone.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": -10,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
					    {
        "question": "I wouldn't care if people died at large amounts if they are not related to me.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 5,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
					    {
        "question": "People should care more about themselves than anyone else.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 5,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
					    {
        "question": "Morality is the most important part of my life, and a big part of my ideas.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 10,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
						    {
        "question": "I apply Morality to all my ideas, and if I do something I think is Immoral, I instantly regret it.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 10,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
						    {
        "question": "The Immoral are Inferior.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 5,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
						    {
        "question": "Morality is objective, thus shouldn't be applied on a universal basis.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": -10,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
						    {
        "question": "The Immoral should be purged.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 10,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
						    {
        "question": "Morality is real and important, and not a spook.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 5,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
						    {
        "question": "Morality comes before anything else.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 10,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
						    {
        "question": "I would not feel anything I were to murder an entire family of innocent people. (You won't get punished)",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": -10,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
						    {
        "question": "Morality does not exist.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": -5,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
						    {
        "question": "Ethics do not matter.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": -5,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
						    {
        "question": "It is natural for humans to be destructive.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 5,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
							    {
        "question": "It is the objective of every man to be as useful as possible.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": -5,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
							    {
        "question": "People's actions should benefit the collective in someway.",
        "effect": {
            "econ": 5,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": -5,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
							    {
        "question": "It is the objective of every human to do what benefits them as individuals",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 5,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
							    {
        "question": "The fact is people are destructive, and stopping that is a waste of time and money.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 5,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
								    {
        "question": "The Individual has no obligation to contribute to the Collective.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 5,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
								    {
        "question": "Every Individual is just another piece of the Collective",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": -10,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
								    {
        "question": "The Individual has no power compared to the Collective.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": -5,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
								    {
        "question": "Individual choices are always right, and should not be influenced by the Collective.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 5,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
								    {
        "question": "Democracy is a failed system, and everything resembeling it is invalid.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": -5,
			"cult": 0,
			"milt": 0,
        }
    },
									    {
        "question": "Every system should have a Hierarchy.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": -5,
			"cult": 0,
			"milt": 0,
        }
    },
									    {
        "question": "Some people are more fit to rule than others, thus they should.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": -5,
			"cult": 0,
			"milt": 0,
        }
    },
									    {
        "question": "Democratic systems are unstable, and dangerous.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": -5,
			"cult": 0,
			"milt": 0,
        }
    },
									    {
        "question": "The People know how to rule better than the Higher-Class.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 5,
			"cult": 0,
			"milt": 0,
        }
    },
									    {
        "question": "The Elite are superior, and are more fit to rule.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": -5,
			"cult": 0,
			"milt": 0,
        }
    },
									    {
        "question": "The Majority knows what is best for the nation.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": -5,
			"cult": 0,
			"milt": 0,
        }
    },
									    {
        "question": "If the Majority likes an idea, it should be implemented no matter how destructive it is.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 5,
			"cult": 0,
			"milt": 0,
        }
    },
									    {
        "question": "The Minority does not matter, the Majority is far more important.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 5,
			"cult": 0,
			"milt": 0,
        }
    },
									    {
        "question": "No one but the people can make good decisions, and the more people who are deciding, the better.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 5,
			"cult": 0,
			"milt": 0,
        }
    },
									    {
        "question": "Democracy is a failed system, and everything resembeling it is invalid.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": -5,
			"cult": 0,
			"milt": 0,
        }
    },
									    {
        "question": "Space is the last frontier.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 5,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
	{
	        "question": "Federal Governments are much more stable than Unitary ones.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": -5,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
	{
	        "question": "Small communes are much more effective at governing themselves than central governments.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": -5,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
	{
	        "question": "We should start colonizing Mars.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 5,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
	{
	        "question": "A City/Commune is more stable than a Nation.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": -5,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
	{
	        "question": "Empires like the Roman Empire, were very effective and gave lots of progress to humanity.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 5,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
	{
	        "question": "The best way of maintaining peace among a people is by letting all ethnic, political, cultural, religious, or any other groups have their own Country.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": -5,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
	{
	        "question": "A single, Intergalactic Space-Empire is something we should strive for.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 10,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
	{
	        "question": "Everyone gets what they want in an Urbanist Society.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": -5,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
	{
	        "question": "If there are other intelligent species somewhere in the universe, we should aim to join our forces and make one, unitary, Inter-Galactic Super-Empire.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 10,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
	{
	        "question": "Humanity was a mistake.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 5,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 5,
        }
    },
	{
	        "question": "My Political ideas are influenced by my Religion.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": -5,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
	{
		        "question": "Religions are dangerous, and slow down Humanity.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 10,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
	{
		        "question": "Religion gives us Truth, and Answers.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": -5,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
	{
		        "question": "I believe in some sort of Mystical/Divine Power.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": -5,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
	{
		        "question": "My Political ideas were influenced by my God, and were meant for me to spread them.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": -10,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
	{
		        "question": "Sacrifices are good as long as they're for some divine or mystical being.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": -10,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
	{
		        "question": "Everything is nothing, and nothing has meaning, it's all just matter.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 10,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
	{
		        "question": "We are all going to die anyway, so this question, and this entire test, is utterly meaningless.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 5,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
	{
		        "question": "My Political ideas are influenced by my Religion.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": -5,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
	{
		        "question": "Without a Divine Being, there is nothing.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": -5,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
	{
		        "question": "My culture is superior to others.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": -5,
			"milt": 0,
        }
    },
		{
		        "question": "The ideas of Darwin can be applied to Humanity.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": -5,
			"milt": 0,
        }
    },
		{
		        "question": "I don't want to get related to outsiders.",
        "effect": {
            "econ": 0,
            "dipl": -5,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": -5,
			"milt": 0,
        }
    },
		{
		        "question": "If you want to live in my country, you should adopt it's culture.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": -5,
			"milt": 0,
        }
    },
		{
		        "question": "Only my culture should exist, and all other cultures are inferior and spooks.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": -10,
			"milt": 0,
        }
    },
		{
		        "question": "All traditions deserve the same amount of respect.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 10,
			"milt": 0,
        }
    },
		{
		        "question": "Anything, including murder and rape, are acceptable as long as they're cultural traditions.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 15,
			"milt": 0,
        }
    },
		{
		        "question": "All cultures that aren't mine should not interact with me, or face eradication.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": -10,
			"milt": 0,
        }
    },
		{
		        "question": "I like to try food from other cultures and nations in resteraunts.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 5,
			"milt": 0,
        }
    },
		{
		        "question": "My culture is just superior to all others, but others can be good aswell.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": -3,
			"milt": 0,
        }
    },
		{
		        "question": "Other cultures are a spook.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": -5,
			"milt": 0,
        }
    },
		{
		        "question": "Our people shouldn't interact with outsiders.",
        "effect": {
            "econ": 0,
            "dipl": -10,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
			{
		        "question": "It would be best if the outside world didn't know about my people or country.",
        "effect": {
            "econ": 0,
            "dipl": -10,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
			{
		        "question": "If I could, I would seperate myself from the rest of society.",
        "effect": {
            "econ": 0,
            "dipl": -5,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
			{
		        "question": "My people deserve better than what the international world offers us.",
        "effect": {
            "econ": 0,
            "dipl": -5,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
			{
		        "question": "There should be no immigration, foreign affairs, contact, or knowledge of my nation.",
        "effect": {
            "econ": 0,
            "dipl": -10,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
			{
		        "question": "Our country should aim to improve relations with other nations, and conduct foreign affairs regularly.",
        "effect": {
            "econ": 0,
            "dipl": 5,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
			{
		        "question": "All foreign affairs are good.",
        "effect": {
            "econ": 0,
            "dipl": 5,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
			{
		        "question": "Businesses should compete worldwide.",
        "effect": {
            "econ": -5,
            "dipl": 5,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
			{
		        "question": "Borders only get in the way of international trade.",
        "effect": {
            "econ": 0,
            "dipl": 10,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
			{
		        "question": "There should be a one world government.",
        "effect": {
            "econ": 0,
            "dipl": 10,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
			{
		        "question": "Violence is not acceptable no matter the circumstances.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": -10,
        }
    },
				{
		        "question": "JUST NUKE EVERYTHING!!!",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 15,
        }
    },
				{
		        "question": "War is the answer to every single problem we can imagine, no matter how small or insignificant.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 10,
        }
    },
				{
		        "question": "Nukes should be used in every war, even small wars and wars on terror.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 10,
        }
    },
				{
		        "question": "Nukes are not acceptable, and should all be destroyed.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": -10,
        }
    },
				{
		        "question": "We should embrace the end.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 5,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 5,
        }
    },
				{
		        "question": "Wars are good.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 5,
        }
    },
				{
		        "question": "There should be no International Law/War Crimes.",
        "effect": {
            "econ": 0,
            "dipl": -5,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 10,
        }
    },
					{
		        "question": "War is necessary, and will always exist as long as there are people around.",
        "effect": {
            "econ": 0,
            "dipl": -5,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 5,
        }
    },
					{
		        "question": "There should be no International Law/War Crimes.",
        "effect": {
            "econ": 0,
            "dipl": -5,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 10,
        }
    },
					{
		        "question": "Technology will solve all of our problems.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": -5,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
						{
		        "question": "It is inevitable that humans will be replaced by machines.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": -10,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
							{
		        "question": "We should preserve nature, rather than upgrading technology.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 5,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
							{
		        "question": "Humanity in a way, was better centuries ago.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 5,
			"hier": 0,
			"rlgs": -5,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
							{
		        "question": "I wouldn't oppose getting Cybernetic Implants (Robot Arms/Legs, Chips, etc.)",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": -5,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
							{
		        "question": "Fully Sentient A.I is too dangerous and should not be invented.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 5,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
							{
		        "question": "Robots and A.I are inherently superior to us puny humans.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": -10,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
							{
		        "question": "It is inevitable that humans will be replaced by machines.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 10,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
								{
		        "question": "No A.I will be able to outmatch humanity.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 5,
			"hier": 0,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
								{
		        "question": "Hierarchies form naturally in society, and we should embrace that.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": -5,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
									{
		        "question": "The Hierarchical Culture of hundreds, if not thousands of years ago, is better than what we have now.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": -10,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
									{
		        "question": "Some groups of people are inherently inferior to others.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": -5,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
									{
		        "question": "Some groups of people should be discriminated against.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": -5,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
									{
		        "question": "If a leader is put into power, he should not be restricted by any means.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": -5,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": -5,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
									{
		        "question": "We should either assimilate or kill anyone who's not in my group.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": -10,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
									{
		        "question": "All people are born equal.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 5,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
									{
		        "question": "All groups of people are equal, and should be treated as such.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 5,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
									{
		        "question": "Everyone, and everything, is created equal.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 10,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
									{
		        "question": "All people are equal, regardless of anything and everything you can think of.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 10,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    },
									{
		        "question": "There should not be a leader in society.",
        "effect": {
            "econ": 0,
            "dipl": 0,
            "civi": 0,
            "morl": 0,
			"ordr": 0,
			"tech": 0,
			"hier": 10,
			"rlgs": 0,
			"rgnl": 0,
			"govt": 0,
			"cult": 0,
			"milt": 0,
        }
    }
];
